version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0.11-alpine

  web:
    build: ./core
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./core/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build:
      context: ./core
    command: celery --app=core worker -l INFO 
    env_file:
      - ./core/.env
    volumes:
      - ./core:/usr/src/app
    depends_on:
      - redis
      - db

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./core/.env

volumes:
  postgres_data:
