# Generated by Django 5.0.6 on 2024-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2550)),
                ("description", models.TextField()),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=2550, null=True)),
                ("gender", models.CharField(blank=True, max_length=2550, null=True)),
                (
                    "minimum_work_experience",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                ("salary", models.CharField(blank=True, max_length=2550, null=True)),
                ("skills", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "job_classification",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "military_service_status",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "hyper_link",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                ("web_app", models.CharField(blank=True, max_length=2550, null=True)),
            ],
        ),
    ]
